input {
  file {
    path => "/opt/fleuris-vault/logs/app.json.log"
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/fleuris.sincedb"
    codec => "json"
  }
}

filter {
  date {
    match => [ "timestamp", "ISO8601" ]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "response_time_ms" => "integer"
      "status_code"      => "integer"
      "user_id"          => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "fleuris-logs-%{+YYYY.MM.dd}"
  }
}
